### ISSUE TITLE
Fire Event At Start

### ISSUE THREAD

**Issue by LukePettway** [Nolanus/ng2-page-scroll#101]
First off, thanks for providing this library, it has been working great so far! One thing I was wondering, is there a plan in the future to possibly include a (pageScrollStart) event? My use case is that I need to close a menu as soon as the anchor is clicked, and currently I can only achieve that after the fact.  

I could always just inject the service and go that route, but I'd imagine it might be a simple feature that a lot of other people may benefit from as well. 

Maybe there is a way to do this, or I am doing something wrong, but I figured I'd at least mention something. Thanks again for this awesome library!

**Comment by Nolanus** [comment]
Hi,

i assume you're using the `pageScroll` directive. You may easily register another click-listener at the anchor-tag and close the menu:

```html
<a href="#section" (click)="closeMenu()" pageScroll >Link</a>
```

Although a click on the a-tag does not guarantee the scroll animation to start (it might fail e.g. due to "target not found" or not take place, as the user already scrolled to the target section), it should suit the described needs.

Let me know if there's a scenario where detailed animation whether the an animation really started could be required.

**Comment by LukePettway** [comment]
@Nolanus Thanks, I think I tried that, but now I'm wondering if I was just doing something wrong. I'll let you know if that works out for me!

**Comment by LukePettway** [comment]
Yep it was me being stupid somewhere, thanks again!
