### ISSUE TITLE
pageScroll override my radio btn click

### ISSUE THREAD

**Issue by ibagaric** [Nolanus/ng2-page-scroll#144]
```
                <label *ngFor="let answer of answers;" 
                       (click)="next(i+1);" 
                       pageScroll href="#question-{{i+1}}" [pageScrollInterruptible]="false"
                       >

                    <input type="radio"
                           name="{{question.idQuestion}}"
                           [value]="answer.idAnswer"
                           [checked]="answer.idAnswer === 1">

                    {{answer.nameInt}}

                </label>
```

Hi, when i click on radio btn that also have pageScroll behavior,  click on radio btn is not registered, while scrolling is fine.

**Comment by Nolanus** [comment]
The click() listener that `pageScroll` directive attaches prevents the default action (https://github.com/Nolanus/ng2-page-scroll/blob/master/src/ng2-page-scroll.directive.ts#L144). This is because otherwise the browser would immediately jump to the respective element with the matching `id` attribute.

You may use the `PageScrollService` and use that to trigger a scroll animation in a custom function (`(click)="customFunc()"`). 
It might as well work to attach the pageScroll directive to a new element that wraps the radioinput and the `answer.nameInt`, but I haven't tried that and only sketched the code:

```
<label *ngFor="let answer of answers;" (click)="next(i+1);">
   <span pageScroll href="#question-{{i+1}}" [pageScrollInterruptible]="false">
         <input type="radio" name="{{question.idQuestion}}" [value]="answer.idAnswer"
 [checked]="answer.idAnswer === 1">
        {{answer.nameInt}}
   </span>
</label>
```

**Comment by ibagaric** [comment]
Thank  you, Nolanus!

even if i separate `pageScroll `from click event it does not work.
So i use `PageScrollService `and now it is working fine! 

maybe you can just update instruction for using ,before i could use `PageScrollService  `i need to `import { PageScrollConfig, PageScrollService, PageScrollInstance } from 'ng2-page-scroll';`
