### ISSUE TITLE
Can't bind to 'pageScrollDuration' since it isn't a known native property

### ISSUE THREAD

**Issue by uzumakinaruto123** [Nolanus/ng2-page-scroll#19]
I am getting above error. If i I remove `[pageScrollDuration]="2000"` , everything works.

**Comment by Nolanus** [comment]
Could you please create a plnkr that reproduces your problem?

**Comment by wuhkuh** [comment]
I am having the exact same issue, but this time it's not restricted to just pageScrollDuration, but all properties of the package.

Example error:
```
Unhandled Promise rejection: Template parse errors:
Can't bind to 'pageScrollInterruptible' since it isn't a known native property
```

Since then I've added it to my vendors folder, and added a map and package entry, to no avail.

**Comment by naveedahmed1** [comment]
@Nolanus can you please add a working plunker of the example? I think it would be really helpful.

**Comment by adriancarriger** [comment]
Here's a [working plunker](http://plnkr.co/edit/w3zNTOoHo8fR7geaz9Vo?p=preview) for RC5 that uses `[pageScrollDuration]="2000"`

Usually when I get an error with `it isn't a known native property` it's because I forgot to add it to the list of directives for the component that uses `pageScroll` (or in RC5 you can optionally add it your module's `declarations` section).
