### ISSUE TITLE
Links not working when using ngFor loop with pageScroll attribute

### ISSUE THREAD

**Issue by rahuldpi** [Nolanus/ng2-page-scroll#192]
While using pageScroll attribute with ngFor loop, the link isn't working. I think because the `href` attribute is getting replaced with the `ng-reflect-href`.

**Source code:**
`<a *ngFor="let section of sections" pageScroll [pageScrollOffset]="50" [pageScrollDuration]="300" [href]="'#'+section.sectionName">{{section.sectionName}}</a>`

**Output:**
`<a _ngcontent-c1="" pagescroll="" ng-reflect-href="#PATIENT IDENTIFICATION" ng-reflect-page-scroll-offset="50" ng-reflect-page-scroll-duration="300" ng-reflect-page-scroll="">PATIENT IDENTIFICATION</a>`

If I remove the pageScroll attribute the link starts functioning normally.

**Source code:**
`<a *ngFor="let section of sections" [href]="'#'+section.sectionName">{{section.sectionName}}</a>`

**Output:**
`<a _ngcontent-c1="" href="#PATIENT IDENTIFICATION">PATIENT IDENTIFICATION</a>`

**Comment by Nolanus** [comment]
Hi @rahuldpi,

please note that `ng-reflect-` attributes are only present in debug mode for debugging purposes (https://stackoverflow.com/questions/43397839/what-does-the-ng-reflect-attribute-do-in-angular2-4). Thus they should have no effect on the functionality of your code.

In your second example they are not generated because there is no directive/component that is accessing them (=> no need for debugging information).

Adding the `pageScroll` directive to a link disables the "default" click behavior by preventing the publication of the click event (compare https://github.com/Nolanus/ng2-page-scroll/blob/master/src/ng2-page-scroll.directive.ts#L148). Thus the link does not functional normal as intended, because the scroll animation should start.

Please double check that the scroll targets (e.g. `<div id="patientIdentification">`) exist on the current page and look in the console for errors/warnings.

**Comment by rahuldpi** [comment]
Thanks, the issue is resolved. As you mentioned, the ID was missing on the page which caused the issue.
