### ISSUE TITLE
Does not work with HashLocationStrategy

### ISSUE THREAD

**Issue by jbeckton** [Nolanus/ng2-page-scroll#3]
Not sure if you did not intend for this to work with HashLocationStrategy or not, the Docs do not mention  if this is supported or not.

In my situation I have to use HashLocationStrategy and still need to scroll to anchors within the page.

![ng2-scroll-errors](https://cloud.githubusercontent.com/assets/2669585/14691699/ec92696e-070f-11e6-9742-80c7b962f17a.png)

**Comment by Nolanus** [comment]
Thanks for pointing that out! As mentioned by [this stackoverflow answer](http://stackoverflow.com/questions/34247981/angular2-navigate-to-anchor-error), the problem is the usage of anchors while using the HashLocationStrategy. So the problem is not related to this directive, but angular2 in general. Nevertheless I will think about a solution.

**Comment by jbeckton** [comment]
I realized the issue with Angular2 after I removed your package and tried to do page anchors and got the same error. I concur, it's not your code it's definitely an issue with Angular2. I guess this is the risks we take while using Beta code for production apps. I will just have to use a different approach and forget about the page anchors for now. I think Angular2 has plans to implement scrollTo functionality just not sure when.

**Comment by Nolanus** [comment]
Please take a look at the updated example app and uncomment the usage for HashLocationStrategy in [main.ts](https://github.com/Nolanus/ng2-page-scroll/blob/master/example/app/main.ts). It worked for me even with the usage of the HashLocationStrategy and across routes.
