### ISSUE TITLE
Horizontal scrolling ?

### ISSUE THREAD

**Issue by arsonik** [Nolanus/ng2-page-scroll#61]
I wanted to create an horizontal scrolling thingy !
like an image gallery where the container take the full screen

The doc says:
"By default the scrollTop property of the body and html element are manipulated."

Does that mean its not even possible ?

**Comment by Nolanus** [comment]
Hi @arsonik, you're right. Currently only vertical scrolling is supported.
However, adding support for horizontal scrolling shouldn't be that hard as we can adjust the [`scrollLeft`](https://developer.mozilla.org/de/docs/Web/API/Element/scrollLeft) property instead of the scrollTop. I'll try to include that in the v4 release.
