### ISSUE TITLE
Using a very low defaultDuration produces unpredictable behavior

### ISSUE THREAD

**Issue by bbottema** [Nolanus/ng2-page-scroll#8]
I'm using a `PageScrollConfig.defaultDuration` of 0 to achieve instant scrolling, but it's jumping to the top of the page instead. If I use a very low value (say 1 ms), then it scrolls to the middle of the page.

**Comment by Nolanus** [comment]
The problem was the order how it handled the scroll position and checking whether we reached the duration time in every interval. Setting the duration 0 now results in immediately jumping to target (4cd1b32f36b216953f4d648af436bf3320e2e64c, 5a24fbec0aa13617cf1bf3008fab5ce54ccb9645). Similar does happen for all duration values that are so small that they would not result in a proper "animation" anyway.
Feel free to test it and share your experiences here!
